const IMAGE_BASE="https://image.tmdb.org/t/p/";
const text=(tag,value,className)=>{const el=document.createElement(tag);if(className)el.className=className;el.textContent=value||"";return el};
const imageUrl=(path,size="w780")=>path?`${IMAGE_BASE}${size}${path}`:"";
const slotOf=item=>item.slot_key||item.slot||"";
function posterCard(item){const card=document.createElement("a");card.className="poster-card";card.href=`detalhe.html?type=${item.media_type==="tv"?"tv":"movie"}&id=${Number(item.id)}`;const frame=document.createElement("span");frame.className="poster-frame";if(item.poster_path){const img=document.createElement("img");img.src=imageUrl(item.poster_path,"w500");img.alt="";img.loading="lazy";frame.append(img)}if(item.vote_average){frame.append(text("b",item.vote_average.toFixed(1),"rating"))}card.append(frame,text("h3",item.title||item.name),text("small",(item.release_date||item.first_air_date||"").slice(0,4)));return card}
function fillRow(id,items=[]){const root=document.getElementById(id);root.replaceChildren(...items.slice(0,6).map(posterCard))}
function ranking(items=[]){const root=document.getElementById("top-rated");root.replaceChildren(...items.slice(0,6).map((item,i)=>{const li=document.createElement("li");li.append(text("b",String(i+1).padStart(2,"0")),text("span",item.title||item.name),text("small",item.vote_average?.toFixed(1)));return li}))}
function hero(item){if(!item)return;const root=document.getElementById("hero");root.setAttribute("aria-busy","false");const bg=root.querySelector(".hero-backdrop");bg.style.backgroundImage=`url(${imageUrl(item.backdrop_path,"original")})`;root.querySelector(".kicker").textContent="DESTAQUE DO DIA";root.querySelector("h1").textContent=item.title||item.name;root.querySelector("p").textContent=item.overview||"Descubra o que está movimentando as telas.";root.onclick=()=>location.href=`detalhe.html?type=${item.media_type==="tv"?"tv":"movie"}&id=${Number(item.id)}`}
function editorialHero(item){if(!item)return;const root=document.getElementById("hero");root.setAttribute("aria-busy","false");root.querySelector(".hero-backdrop").style.backgroundImage=item.image_url?`url(${item.image_url})`:"";root.querySelector(".kicker").textContent=(item.category||"DESTAQUE EDITORIAL").replaceAll("-"," ").toUpperCase();root.querySelector("h1").textContent=item.title;root.querySelector("p").textContent=item.description||"Leia a matéria completa.";root.onclick=()=>location.href=`materia.html?id=${Number(item.id)}`}
async function loadCatalog(){try{const r=await fetch("/api/catalog",{cache:"no-store"});if(!r.ok)throw 0;const d=await r.json();hero(d.trending?.results?.[0]);fillRow("now-playing",d.now_playing?.results);fillRow("streaming-list",d.streaming?.results);fillRow("series-list",(d.trending?.results||[]).filter(x=>x.media_type==="tv"));ranking(d.top_rated?.results);const trend=document.getElementById("trending-strip");trend.replaceChildren(...(d.trending?.results||[]).slice(0,5).map(x=>text("span",x.title||x.name)));const featured=d.upcoming?.results?.[0];if(featured){const t=document.getElementById("trailer-feature");t.style.backgroundImage=`linear-gradient(0deg,rgba(0,0,0,.75),transparent),url(${imageUrl(featured.backdrop_path,"original")})`;t.querySelector("span").textContent=featured.title;t.onclick=()=>location.href=`detalhe.html?type=movie&id=${Number(featured.id)}`}}catch{document.querySelector(".hero .kicker").textContent="CATÁLOGO TEMPORARIAMENTE INDISPONÍVEL"}}
function newsCard(item){const a=document.createElement("a");a.className="news-card";a.href=`materia.html?id=${Number(item.id)}`;if(item.image_url){const img=document.createElement("img");img.src=item.image_url;img.alt="";img.loading="lazy";a.append(img)}a.append(text("small",(item.category||"Cinema").replaceAll("-"," ")),text("h3",item.title));return a}
async function loadNews(){try{const r=await fetch("/api/articles",{cache:"no-store"});if(!r.ok)return;const p=await r.json(),items=Array.isArray(p)?p:p.articles||[];if(!items.length)return;const bySlot=new Map(items.filter(x=>slotOf(x)).map(x=>[slotOf(x),x]));const lead=bySlot.get("cm_news_lead");if(lead)editorialHero(lead);const ticker=[1,2,3].map(i=>bySlot.get(`cm_ticker_${i}`)).filter(Boolean);if(ticker.length)document.getElementById("trending-strip").replaceChildren(...ticker.map(x=>{const a=text("a",x.title);a.href=`materia.html?id=${Number(x.id)}`;return a}));const used=new Set([lead,...ticker].filter(Boolean).map(x=>x.id));const cards=[];for(let i=1;i<=6;i++){const item=bySlot.get(`cm_news_${i}`);if(item&&!used.has(item.id)){cards.push(item);used.add(item.id)}}for(const item of items){if(cards.length>=6)break;if(!used.has(item.id)){cards.push(item);used.add(item.id)}}document.getElementById("editorial-news").replaceChildren(...cards.map(newsCard))}catch{}}
loadCatalog().finally(loadNews);
