const IMAGE_BASE="https://image.tmdb.org/t/p/";
const HUB="https://hub.cm.com.br";
const text=(tag,value,className)=>{const el=document.createElement(tag);if(className)el.className=className;el.textContent=value||"";return el};
const imageUrl=(path,size="w780")=>path?IMAGE_BASE+size+path:"";
const slotOf=item=>item.slot_key||item.slot||"";
const fresh=url=>url+(url.includes("?")?"&":"?")+"refresh="+Date.now();
function posterCard(item){const card=document.createElement("a");card.className="poster-card";card.href="detalhe.html?type="+(item.media_type==="tv"?"tv":"movie")+"&id="+Number(item.id);const frame=document.createElement("span");frame.className="poster-frame";if(item.poster_path){const img=document.createElement("img");img.src=imageUrl(item.poster_path,"w500");img.alt="";img.loading="lazy";frame.append(img)}if(item.vote_average)frame.append(text("b",item.vote_average.toFixed(1),"rating"));card.append(frame,text("h3",item.title||item.name),text("small",(item.release_date||item.first_air_date||"").slice(0,4)));return card}
function fillRow(id,items=[]){document.getElementById(id)?.replaceChildren(...items.slice(0,6).map(posterCard))}
function ranking(items=[]){document.getElementById("top-rated")?.replaceChildren(...items.slice(0,6).map((item,i)=>{const li=document.createElement("li");li.append(text("b",String(i+1).padStart(2,"0")),text("span",item.title||item.name),text("small",item.vote_average?.toFixed(1)));return li}))}
function hero(item){if(!item)return;const root=document.getElementById("hero");root.setAttribute("aria-busy","false");root.querySelector(".hero-backdrop").style.backgroundImage="url("+imageUrl(item.backdrop_path,"original")+")";root.querySelector(".kicker").textContent="DESTAQUE DO DIA";root.querySelector("h1").textContent=item.title||item.name;root.querySelector("p").textContent=item.overview||"Descubra o que está movimentando as telas.";root.onclick=()=>location.href="detalhe.html?type="+(item.media_type==="tv"?"tv":"movie")+"&id="+Number(item.id)}
function editorialHero(item){if(!item)return;const root=document.getElementById("hero");root.setAttribute("aria-busy","false");root.querySelector(".hero-backdrop").style.backgroundImage=item.image_url?"url("+item.image_url+")":"";root.querySelector(".kicker").textContent=(item.category||"DESTAQUE EDITORIAL").replaceAll("-"," ").toUpperCase();root.querySelector("h1").textContent=item.title;root.querySelector("p").textContent=item.description||"Leia a matéria completa.";root.onclick=()=>location.href="materia.html?id="+Number(item.id)}
async function loadCatalog(){try{const r=await fetch(fresh(HUB+"/api/v1/cinema/home"),{cache:"no-store",signal:AbortSignal.timeout(9000)});if(!r.ok)throw 0;const d=await r.json();fillRow("now-playing",d.now_playing?.results);fillRow("streaming-list",d.streaming?.results);fillRow("series-list",(d.trending?.results||[]).filter(x=>x.media_type==="tv"));ranking(d.top_rated?.results);const featured=d.upcoming?.results?.[0];if(featured){const t=document.getElementById("trailer-feature");t.style.backgroundImage="linear-gradient(0deg,rgba(0,0,0,.75),transparent),url("+imageUrl(featured.backdrop_path,"original")+")";t.querySelector("span").textContent=featured.title;t.onclick=()=>location.href="detalhe.html?type=movie&id="+Number(featured.id)}return{lead:d.trending?.results?.[0],ticker:(d.trending?.results||[]).slice(0,5)}}catch{return{lead:null,ticker:[]}}}
function newsCard(item){const a=document.createElement("a");a.className="news-card";a.href="materia.html?id="+Number(item.id);if(item.image_url){const img=document.createElement("img");img.src=item.image_url;img.alt="";img.loading="lazy";a.append(img)}a.append(text("small",(item.category||"Cinema").replaceAll("-"," ")),text("h3",item.title));return a}
async function loadNews(){try{const r=await fetch(fresh(HUB+"/api/v1/sites/by-domain/articles?domain=revistacinemagazine.com.br"),{cache:"no-store",signal:AbortSignal.timeout(9000)});if(!r.ok)throw 0;const p=await r.json(),items=Array.isArray(p)?p:p.articles||[];if(!items.length)return{lead:null,ticker:[],cards:[]};const bySlot=new Map;items.filter(x=>slotOf(x)).forEach(x=>{if(!bySlot.has(slotOf(x)))bySlot.set(slotOf(x),x)});const lead=bySlot.get("cm_news_lead");const ticker=[1,2,3].map(i=>bySlot.get("cm_ticker_"+i)).filter(Boolean);const used=new Set([lead,...ticker].filter(Boolean).map(x=>x.id));const cards=[];for(let i=1;i<=6;i++){const item=bySlot.get("cm_news_"+i);if(item&&!used.has(item.id)){cards.push(item);used.add(item.id)}}for(const item of items){if(cards.length>=6)break;if(!used.has(item.id)){cards.push(item);used.add(item.id)}}return{lead,ticker,cards}}catch{return{lead:null,ticker:[],cards:[]}}}
function renderNews(news){const root=document.getElementById("editorial-news");if(!root)return;root.replaceChildren(...news.cards.map(newsCard));if(!news.cards.length)root.append(text("div","As matérias publicadas pelo Content Hub aparecerão aqui.","empty-card"))}
function renderTicker(news,catalog){const ticker=news.ticker.length?news.ticker:catalog.ticker;const root=document.getElementById("trending-strip");if(!root)return;root.replaceChildren(...ticker.map(x=>{const a=text(news.ticker.length?"a":"span",x.title||x.name);if(news.ticker.length)a.href="materia.html?id="+Number(x.id);return a}))}
let refreshInFlight=false,refreshToken=0;
async function refreshHome(){if(refreshInFlight)return;refreshInFlight=true;const token=++refreshToken;try{const [catalog,news]=await Promise.all([loadCatalog(),loadNews()]);if(token!==refreshToken)return;renderNews(news);if(news.lead)editorialHero(news.lead);else if(catalog.lead)hero(catalog.lead);renderTicker(news,catalog)}finally{refreshInFlight=false}}
refreshHome();setInterval(()=>{if(document.visibilityState==="visible")refreshHome()},60000);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")refreshHome()});
