const IMAGE_BASE="https://image.tmdb.org/t/p/";
const text=(tag,value,className)=>{const el=document.createElement(tag);if(className)el.className=className;el.textContent=value||"";return el};
const imageUrl=(path,size="w780")=>path?`${IMAGE_BASE}${size}${path}`:"";
function posterCard(item){const card=document.createElement("a");card.className="poster-card";card.href=`detalhe.html?type=${item.media_type==="tv"?"tv":"movie"}&id=${Number(item.id)}`;const frame=document.createElement("span");frame.className="poster-frame";if(item.poster_path){const img=document.createElement("img");img.src=imageUrl(item.poster_path,"w500");img.alt="";img.loading="lazy";frame.append(img)}if(item.vote_average){frame.append(text("b",item.vote_average.toFixed(1),"rating"))}card.append(frame,text("h3",item.title||item.name),text("small",(item.release_date||item.first_air_date||"").slice(0,4)));return card}
function fillRow(id,items=[]){const root=document.getElementById(id);root.replaceChildren(...items.slice(0,6).map(posterCard))}
function ranking(items=[]){const root=document.getElementById("top-rated");root.replaceChildren(...items.slice(0,6).map((item,i)=>{const li=document.createElement("li");li.append(text("b",String(i+1).padStart(2,"0")),text("span",item.title||item.name),text("small",item.vote_average?.toFixed(1)));return li}))}
function hero(item){if(!item)return;const root=document.getElementById("hero");root.setAttribute("aria-busy","false");const bg=root.querySelector(".hero-backdrop");bg.style.backgroundImage=`url(${imageUrl(item.backdrop_path,"original")})`;root.querySelector(".kicker").textContent="DESTAQUE DO DIA";root.querySelector("h1").textContent=item.title||item.name;root.querySelector("p").textContent=item.overview||"Descubra o que está movimentando as telas.";root.onclick=()=>location.href=`detalhe.html?type=${item.media_type==="tv"?"tv":"movie"}&id=${Number(item.id)}`}
async function loadCatalog(){try{const r=await fetch("/api/catalog",{cache:"no-store"});if(!r.ok)throw 0;const d=await r.json();hero(d.trending?.results?.[0]);fillRow("now-playing",d.now_playing?.results);fillRow("streaming-list",d.streaming?.results);fillRow("series-list",(d.trending?.results||[]).filter(x=>x.media_type==="tv"));ranking(d.top_rated?.results);const trend=document.getElementById("trending-strip");trend.replaceChildren(...(d.trending?.results||[]).slice(0,5).map(x=>text("span",x.title||x.name)));const featured=d.upcoming?.results?.[0];if(featured){const t=document.getElementById("trailer-feature");t.style.backgroundImage=`linear-gradient(0deg,rgba(0,0,0,.75),transparent),url(${imageUrl(featured.backdrop_path,"original")})`;t.querySelector("span").textContent=featured.title;t.onclick=()=>location.href=`detalhe.html?type=movie&id=${Number(featured.id)}`}}catch{document.querySelector(".hero .kicker").textContent="CATÁLOGO TEMPORARIAMENTE INDISPONÍVEL"}}
function newsCard(item){const a=document.createElement("a");a.className="news-card";a.href=`materia.html?id=${Number(item.id)}`;if(item.image_url){const img=document.createElement("img");img.src=item.image_url;img.alt="";img.loading="lazy";a.append(img)}a.append(text("small",(item.category||"Cinema").replaceAll("-"," ")),text("h3",item.title));return a}
async function loadNews(){try{const r=await fetch("/api/articles",{cache:"no-store"});if(!r.ok)return;const p=await r.json(),items=Array.isArray(p)?p:p.articles||[];if(items.length)document.getElementById("editorial-news").replaceChildren(...items.slice(0,6).map(newsCard))}catch{}}
loadCatalog();loadNews();
